version: '3.1'

services:
  django-api:
    container_name: django-api
    restart: always
    working_dir: '/usr/test'
    build: 
      context: .
      dockerfile: django.DockerFile
    env_file:
      - .env
    volumes:
      - ./server:/usr/test
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - django-pgadmin

  django-db:
    image: postgres:latest
    container_name: django-db
    hostname: ${POSTGRES_HOST}
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"

  django-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: django-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_LISTEN_PORT}:80"
    depends_on:
      - django-db